# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua



$mainMod = SUPER
$terminal = kitty
$fileManager = dolphin
$menu = wofi
workspace = 1, persistent:true
workspace = 2, persistent:true
bind = $mainMod, Q, exec, $terminal


animations {
	enabled = true
	animation = workspaces, 1, 4, default, slidevert
}
bind = $mainMod, C, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, SPACE, togglefloating,
bind = $mainMod, V, exec, code
bind = $mainMod, F, fullscreen, 1
bind = $mainMod, R, exec, $menu
bind = $mainMod, B, exec, brave
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d
bind = SUPER_SHIFT, right, workspace, 2
bind = SUPER_SHIFT, left,  workspace, 1
bind = SUPER_SHIFT, up, workspace, 1
bind = SUPER_SHIFT, down, workspace, 2
bind = SUPER CTRL, up, exec ,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bind = SUPER CTRL, DOWN, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
#bind = SUPER_SHIFT, right, exec, hyprctl dispatch workspace $(( $(hyprctl activeworkspace -j | jq '.id') % 2 + 1 ))
#bind = SUPER_SHIFT, left,  exec, hyprctl dispatch workspace $(( 3 - $(hyprctl activeworkspace -j | jq '.id') ))
