#preload = /home/popopopo/wallpapers/wallpaper1.jp
#wallpaper = ,/home/popopopo/wallpapers/wallpaper1.jpg

wallpaper {
    monitor = 
    path = /home/popopopo/wallpapers/wall3.jpg
    fit_mode = cover
}
splash = false
